# Generated by Django 4.1.3 on 2022-11-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='createdDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='options',
            field=models.TextField(default=12121212),
            preserve_default=False,
        ),
    ]
